version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
volumes:
  db:
